modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
showAsResourcePack=false

[[mods]]
  modId="friendlyfire"
  version="beta_1.0"
  displayName="Friendly Fire"
  authors="MsDogGirl"
  description='''
  Friendly fire mod that adds a button to disable the ability to attack configurable mobs.
  '''

